<!-- TAGS: ethics -->
<!-- DATE: 2019-07 -->
<h1>My passionate, complicated relationship with effective altruism</h1>

<p>I came across Peter Singer’s most famous ideas during my last semester of high school. I was taking a class on the philosophy of ethics from UVU. After struggling through some excessively wordy defense of deontological morality, I started flipping absentmindedly through the textbook (which was essentially a compilation of diverse philosophical ideas about morality), and found Peter Singer’s “Famine, Affluence, and Morality.” I read the entire thing (as well as a few other essays making similar arguments) and was, at the time, quite convinced. <span id="more-227"></span>The main takeaways I got were the following:</p>
<ul>
<li>If it is within our power to reduce or eliminate suffering, we should do so.</li>
<li>Suffering that occurs at a distance (e.g. in poor, developing countries) is morally relevant.</li>
<li>Suffering due to poverty does not need to exist. It should be possible to eliminate this sort of suffering given a well-thought-out, coordinated effort.</li>
<li>Almost anyone in a country like the U.S. is hugely more wealthy than the typical person in countries where the worst poverty exists. This wealth disparity can be leveraged to have an outsized impact on improving the well-being of the global poor.</li>
</ul>

<!-- ENDPREVIEW -->

<p>One thing led to another, and before I knew it I had spent hours perusing websites like <a href="https://www.thelifeyoucansave.org">https://www.thelifeyoucansave.org</a>, <a href="https://www.givewell.org">https://www.givewell.org</a>, and <a href="https://80000hours.org">https://80000hours.org</a>. I had ventured for the first time into the weird and wonderful world of “effective altruism.”</p>
<p>According to my friend Wikipedia, effective altruism is “a philosophy and social movement that uses evidence and reasoning to determine the most effective ways to benefit others.” It should not be surprising that this caught my interest. I have always been of the mindset that if a problem is important, then it should be carefully, rationally, and <em>ambitiously</em> attacked. This is exactly what effective altruists aim to due with the (obviously important) problem of reducing suffering and improving well-being.</p>
<p>There are, of course, problems with this way of thinking. I can, for example, push back against the points I listed above:</p>
<ul>
<li>Eliminating or reducing suffering is intuitively attractive, but there are of course other imperatives that could conceivably take precedence in a moral sense.</li>
<li>The well-being of those in one’s proximity (e.g. in one’s own family or community) is arguably more important than the well-being of people in distant places.</li>
<li>The problem of eliminating suffering from poverty is not at all a simple problem to tackle. It is highly context-dependent, enmeshed with cultural and historical factors, and requires large-scale cooperation.</li>
<li>People in wealthy countries do generally have disproportionate leverage, but it’s not obvious how much we should be willing to sacrifice to help others. Taking a hit in one’s standard of living to help someone you will never meet is not intuitively attractive. It should also be noted that conditions of (relative) poverty do exist in some settings even with rich countries like the U.S. (Just cross west of Line Ave. in Shreveport.)</li>
</ul>
<p>These considerations, among others, bounced around in a rather disorganized way in my mental space for several years, including the time I spent as a missionary in Mississippi and Louisiana. I had wanted to be a missionary because I believed it was a means to have an impact in people’s lives in an extremely significant and (very) long-lasting way. However, I progressively became frustrated with the basis in truth of the things I was sharing and of the efficacy of my missionary efforts to help people in the ways that they so clearly needed to be helped. I clearly remember several occasions where I was overwhelmed by an intense (and frankly, religious) desire to dedicate myself to helping the suffering people I saw all around me. As I wrote later,</p>
<blockquote><p>I was zealously devoted to the project of relieving some of the suffering and unfairness so abundant in this world and honestly no longer cared about the nit-picky doctrines that get so much play whenever human beings decide to create churches.</p></blockquote>
<p>The relationship between all this and my changing religious convictions is a different story (though I’ll tell you more about it if you ask). The point I’m trying to make is that my interest in making a positive social impact was not merely cerebral; I was (and still am) strongly motivated by that goal. I hate the idea that at this very moment, there are many, many people consumed by intense emotional or physical pain, and you and I are sitting here, absorbed by our quotidian concerns, doing very little to assist those people. This sort of disposition seems to be rather common among self-proclaimed effective altruists – I recently came across this account about the philosopher Derek Parfit (quoted from <a href="https://slatestarcodex.com/2017/08/16/fear-and-loathing-at-effective-altruism-global-2017/">https://slatestarcodex.com/2017/08/16/fear-and-loathing-at-effective-altruism-global-2017/</a>):</p>
<blockquote><p>When I was interviewing him for the first time, for instance, we were in the middle of a conversation and suddenly he burst into tears. It was completely unexpected, because we were not talking about anything emotional or personal, as I would define those things. I was quite startled, and as he cried I sat there rewinding our conversation in my head, trying to figure out what had upset him. Later, I asked him about it. It turned out that what had made him cry was the idea of suffering. We had been talking about suffering in the abstract. I found that very striking.</p></blockquote>
<p>After getting back from the South, I paid my fascination with effective altruism some attention by beginning to study economics, a discipline that I figured would help me to have a greater impact in the areas I cared about. (As a side note, I was pleasantly surprised to find that economics is also an excellent arena for mathematically inclined people to scratch their intellectual itch. If you think that real analysis is not all that practically useful, you probably don’t know much about microeconomic theory.) I still had (/have) some lingering misgivings, though, among them:</p>
<ul>
<li>Who says that morality is constrained to a utilitarian framework? It is attractive to analyze things based on their consequences in terms of utility (their effect on total well-being) since it is mathematically much more tractable, but this is clearly <em>not</em> how people generally think about what is right and wrong, as can be demonstrated with any number of thought experiments. The decision to take a utilitarian stance is at some level arbitrary.</li>
<li>How do we decide whose welfare to pay attention to? I can get behind health programs in Sub-Saharan Africa, but the moral calculus becomes bizarrely complicated when considering efforts to maximize the well-being of people in the far-off future or creatures of other species. I was recently completely befuddled after listening to a podcast about attempts to quantify the suffering faced by Earth’s invertebrate population.</li>
<li>How do we deal with the unintuitive ethics of large populations or low-risk events? Should we, for example, be very concerned about things with ill-defined probabilities but potentially disastrous consequences like risks from synthetic biology, nuclear weapons, or artificial intelligence?</li>
</ul>
<p>In general, the basic idea of pairing one’s moral intuitions with a careful and intelligent pragmatism is very attractive. However, this way of thinking can easily lead to outwardly strange conclusions. Effective altruism is extremely appealing to me on both an intuitive and a rational level, although I'm still working out how I feel about some of the details.</p>